In [1]:
import torch
import math

In [2]:
vector1 = torch.arange(5).float().reshape(-1, 1)
vector1

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [3]:
vector1.shape

torch.Size([5, 1])

In [4]:
vector2 = torch.arange(12/2).reshape(-1, 1)
vector2

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.]])

In [5]:
-2*vector2*math.log(10000)/1

tensor([[ -0.0000],
        [-18.4207],
        [-36.8414],
        [-55.2620],
        [-73.6827],
        [-92.1034]])

In [6]:
vector3 = torch.e**(-2*vector2*math.log(10000)/1).T
vector3

tensor([[1.0000e+00, 1.0000e-08, 1.0000e-16, 1.0000e-24, 1.0000e-32, 9.9999e-41]])

In [7]:
position_matrix = torch.matmul(vector1, vector3)
position_matrix

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.0000e-08, 1.0000e-16, 1.0000e-24, 1.0000e-32, 9.9999e-41],
        [2.0000e+00, 2.0000e-08, 2.0000e-16, 2.0000e-24, 2.0000e-32, 2.0000e-40],
        [3.0000e+00, 3.0000e-08, 3.0000e-16, 3.0000e-24, 3.0000e-32, 3.0000e-40],
        [4.0000e+00, 4.0000e-08, 4.0000e-16, 4.0000e-24, 4.0000e-32, 4.0000e-40]])

In [8]:
cosine_matrix = torch.cos(position_matrix)
cosine_matrix

tensor([[ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
        [ 0.5403,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
        [-0.4161,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
        [-0.9900,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
        [-0.6536,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000]])

In [9]:
sine_matrix = torch.sin(position_matrix)
sine_matrix

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00],
        [ 8.4147e-01,  1.0000e-08,  1.0000e-16,  1.0000e-24,  1.0000e-32,
          9.9999e-41],
        [ 9.0930e-01,  2.0000e-08,  2.0000e-16,  2.0000e-24,  2.0000e-32,
          2.0000e-40],
        [ 1.4112e-01,  3.0000e-08,  3.0000e-16,  3.0000e-24,  3.0000e-32,
          3.0000e-40],
        [-7.5680e-01,  4.0000e-08,  4.0000e-16,  4.0000e-24,  4.0000e-32,
          4.0000e-40]])

In [10]:
# 1. Create an empty matrix of shape (num_of_tokens, d_model)
pe = torch.zeros(5, 12)

# 2. Fill the even columns (0, 2, 4...) with sine_matrix
pe[:, 0::2] = sine_matrix

# 3. Fill the odd columns (1, 3, 5...) with cosine_matrix
pe[:, 1::2] = cosine_matrix

In [11]:
pe

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,
          0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  1.0000e-08,  1.0000e+00,  1.0000e-16,
          1.0000e+00,  1.0000e-24,  1.0000e+00,  1.0000e-32,  1.0000e+00,
          9.9999e-41,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  2.0000e-08,  1.0000e+00,  2.0000e-16,
          1.0000e+00,  2.0000e-24,  1.0000e+00,  2.0000e-32,  1.0000e+00,
          2.0000e-40,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  3.0000e-08,  1.0000e+00,  3.0000e-16,
          1.0000e+00,  3.0000e-24,  1.0000e+00,  3.0000e-32,  1.0000e+00,
          3.0000e-40,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  4.0000e-08,  1.0000e+00,  4.0000e-16,
          1.0000e+00,  4.0000e-24,  1.0000e+00,  4.0000e-32,  1.0000e+00,
          4.0000e-40,  1.0000e+00]])

In [16]:
class PositionalEncoding():
    """
    Create a Positional Encoding Layer
    """

    def __init__(self):
        pass

    # Recieve a 2d matrix
    def forward(self, input_tensor: torch.tensor) -> torch.tensor:
        num_of_tokens = input_tensor.shape[1]
        self.d_model = input_tensor.shape[2]
        vector1 = torch.arange(num_of_tokens).reshape(-1, 1).float()
        # Vector from 0 to n-1 Shape(n, 1)

        vector2 = torch.arange(self.d_model/2).reshape(-1, 1)
        vector3 = torch.e**(-2*vector2*math.log(10000)/self.d_model).T
        # Vector for division terms Shape(1, d_model)

        matrix = torch.matmul(vector1, vector3)
        # Matrix with shape(num_of_tokens, d_model/2)

        cosine_matrix = torch.cos(matrix)
        sine_matrix = torch.sin(matrix)
        
        # 1. Create an empty matrix of shape (num_of_tokens, d_model)
        pe_matrix = torch.zeros(num_of_tokens, self.d_model)

        # 2. Fill the even columns (0, 2, 4...) with sine_matrix
        pe_matrix[:, 0::2] = sine_matrix

        # 3. Fill the odd columns (1, 3, 5...) with cosine_matrix
        pe_matrix[:, 1::2] = cosine_matrix
        
        output_tensor = input_tensor + pe_matrix

        return output_tensor

In [19]:
pe_layer = PositionalEncoding() # Args: d_model

In [20]:
dummy_input = torch.tensor([[[-2.3714, -0.3812, -1.7202, -1.6734],
        [-1.0599,  1.1760, -0.7231, -4.8346],
        [-1.4924,  0.8261,  3.3299, -1.2870]]])

In [21]:
dummy_output = pe_layer.forward(dummy_input)
dummy_output

tensor([[[-2.3714,  0.6188, -1.7202, -0.6734],
         [-0.2184,  1.7163, -0.7131, -3.8347],
         [-0.5831,  0.4100,  3.3499, -0.2872]]])